### ISSUE TITLE
desktop icon art for space shooter

### ISSUE THREAD

**Issue by Zeelot** [codeghetti/seagulls-py#104]
I think they should  be 256x256 pixels but anything square should do!

**Comment by ToddiusNoobius** [comment]
![image](https://user-images.githubusercontent.com/80657258/158075397-90eaf30e-e2c5-4825-9366-40dce507932a.png)

**Comment by ToddiusNoobius** [comment]
With slightly thinner/smaller laser: 
![image](https://user-images.githubusercontent.com/80657258/158075670-d2c5b361-f24f-4bf9-839f-6be9c7556ea8.png)

**Comment by ToddiusNoobius** [comment]
![ShooterDesktopIconFinal](https://user-images.githubusercontent.com/80657258/159844152-712a3ac1-69cd-4472-8a1c-a88820a9a410.png)

**Comment by Zeelot** [comment]
we did this!
